name       : haskell-asn1-parse
version    : 0.9.5
release    : 3
source     :
    - https://hackage.haskell.org/package/asn1-parse-0.9.5/asn1-parse-0.9.5.tar.gz : 8f1fe1344d30b39dc594d74df2c55209577722af1497204b4c2b6d6e8747f39e
license    : BSD-3-Clause
component  : programming.haskell
summary    : Simple monadic parser for ASN1 stream types, when ASN1 pattern matching is not convenient.
description: |
    Simple monadic parser for ASN1 stream types, when ASN1 pattern matching is not convenient.
builddeps  :
    - haskell-asn1-encoding-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - haskell-asn1-encoding-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
