name       : haskell-asn1-parse
version    : 0.9.4
release    : 2
source     :
    - http://hackage.haskell.org/package/asn1-parse-0.9.4/asn1-parse-0.9.4.tar.gz : c6a328f570c69db73f8d2416f9251e8a03753f90d5d19e76cbe69509a3ceb708
license    : BSD-3-Clause
component  : programming.haskell
summary    : Simple monadic parser for ASN1 stream types, when ASN1 pattern matching
    is not convenient.
description: "Simple monadic parser for ASN1 stream types, when ASN1 pattern matching\
    \ is not convenient. \n"
builddeps  :
    - haskell-asn1-encoding
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
